### ISSUE TITLE
Sample VC document uses conflicting contexts

### ISSUE THREAD

**Issue by tmarkovski** [mattrglobal/jsonld-signatures-bbs#105]
The test documents [test_vc.json](https://github.com/mattrglobal/jsonld-signatures-bbs/blob/master/__tests__/__fixtures__/data/test_vc.json) and [test_signed_vc.json](https://github.com/mattrglobal/jsonld-signatures-bbs/blob/master/__tests__/__fixtures__/data/test_signed_vc.json) require contexts that are conflicting and unable to be processed. For example the term `Ed25519Signature2018` is defined in both `https://www.w3.org/2018/credentials/v1` and `https://w3id.org/security/v3-unstable` as `protected`. This breaks LD tooling.
Temporary fix that passes is to revert `security-v3` to `https://w3c-ccg.github.io/ldp-bbs2020/contexts/v1`.
I'm assuming this issue may be tracked elsewhere, I just ran into it trying to use the test vectors.

**Comment by kdenhartog** [comment]
Yeah this happens when the documentLoader you're using remotely fetches the contexts (security-v3 and credentials). I've been working on solving the problems for this in the remote contexts but we're somewhat blocked by how to handle this in the VC context because it's the one causing the issue with poorly defined LDP suite terms. Most of this work has been tracked in the [security-v3 repo issues](https://github.com/w3c-ccg/security-vocab/issues) with a few other tidbits in the VC repo and mailing list.

To resolve this most easily without having to switch the context copy the local contexts stored [here](https://github.com/mattrglobal/jsonld-signatures-bbs/tree/master/__tests__/__fixtures__/contexts). They override the remote contexts (essentially change what gets loaded into the documentLoader) to remove the 4 LDP suites defined in the VC context which are causing the problem. In particular the 4 are, `EcdsaSecp256k1Signature2019`, `EcdsaSecp256r1Signature2019`, `Ed25519Signature2018`, `RsaSignature2018`. While none of these are in use because of the way the documentLoader handles the protected term it causes issues for documentLoader which throws the error.

**Comment by tmarkovski** [comment]
@kdenhartog That did the trick! Cheers
