### ISSUE TITLE
https://w3id.org/security/v3-unstable -> https://w3id.org/security/bbs/v1

### ISSUE THREAD

**Issue by OR13** [mattrglobal/jsonld-signatures-bbs#111]
I think its better to use `https://w3id.org/security/bbs/v1` instead of sec-v3.... We need to move towards sec-v3 flattening common vocab from v1 and v2 and not defining suites at all.

**Comment by tplooker** [comment]
@OR13 agree however `https://w3id.org/security/bbs/v1` does not define the `proof` term which is required in several operations with linked data proofs. We perhaps need a seperate context definition just for that term.

**Comment by kdenhartog** [comment]
I think we could add the proof property in via a scoped context so that we could move to the bbs context while still being able to keep it down to a single context. We might need to check if that term will cause redefinition issues with the vc context as well, but it would be good to figure out a way to handle it that for VCs and for general JSON-LD documents.

**Comment by vongohren** [comment]
Im currently getting this issue with the sample setup here. Related to this url

![image](https://user-images.githubusercontent.com/1012055/113488522-02b4cd80-94bf-11eb-804c-b950426f56e5.png)

@tplooker @kdenhartog any idea why it fails to reference? 

Just trying to run the sample setup in this repo, with the same json ld file

**Comment by tplooker** [comment]
the v0.9.0 release in progress will address this

**Comment by tplooker** [comment]
Closed via v0.9.0 release
