### ISSUE TITLE
Question: How to generate a dynamic key pair that works with the samples? 

### ISSUE THREAD

**Issue by smithbk** [mattrglobal/jsonld-signatures-bbs#141]
This is a question, not a bug (I assume).  Is there a forum (e.g. rocket chat or slack channel) in which to ask these questions?

That said, my question is how to generate a dynamic key pair that works with the samples?  I am trying to write an issuer and holder to implement an issuance flow.

I am doing the same as found in the demo_single.ts sample except instead of loading the static key pair as is done at https://github.com/mattrglobal/jsonld-signatures-bbs/blob/master/sample/ts-node/src/demo_single.ts#L65, I am dynamically generating the key pair by calling "Bls12381G2KeyPair.generate()" as is required by a real issuer.  The sign operation does not return an error but the verify fails with the following error:

`
No "verificationMethod" found in proof.
at BbsBlsSignature2020.getVerificationMethod (node_modules/@mattrglobal/jsonld-signatures-bbs/src/BbsBlsSignature2020.ts:333:13
`

When I look at the static key pair that is loaded from https://github.com/mattrglobal/jsonld-signatures-bbs/blob/master/sample/ts-node/src/data/keyPair.json, it has an "id" field from which the verificationMethod is derived; however, when I generate a key pair using "Bls12381G2KeyPair.generate()", it is of the following form and does not have an "id" field.

`
{ 
  "type":"Bls12381G2Key2020",
  "privateKeyBuffer":, ...,
  "publicKeyBuffer": ...
}
`

Any help is appreciated.

**Comment by TimoGlastra** [comment]
The key needs to have a verificationMethod identifier. This should then be resolvable in your application.

The tests in this library have a custom resolver that resolves to the specific key so it can be used for verification. https://github.com/mattrglobal/jsonld-signatures-bbs/blob/3000f3cecc04310b5b99acb969f105d6156e2e55/__tests__/__fixtures__/customDocumentLoader.ts#L34

So you'd need to set up a local document resolver that can resolve the key/did document. You can either create a fake did (as is done in the tests in this library). Or plug in a real did resolver (such as `did:key` to use real dids)

**Comment by OR13** [comment]
For example G2 / G1 keys: https://did.key.transmute.industries/generate/bls12381?seed=1510007de9c70aa6ce0c5c2c85d9c2f5debc154abb71c3080c6f0345262b7165

**Comment by kdenhartog** [comment]
> This is a question, not a bug (I assume). Is there a forum (e.g. rocket chat or slack channel) in which to ask these questions?

This is actually the best place for this. Sorry for the delay on it though.

As for your question, it appears your failing because your key has no associated verificationMethod. In other words @TimoGlastra hit in on the head about being able to resolve the did document that the public key is associated with. In the single_demo case the documentLoader is able to resolve the `did:example:489398593` did which resolves to the did document located in the following file: https://github.com/mattrglobal/jsonld-signatures-bbs/blob/master/sample/ts-node/src/data/controllerDocument.json

This is almost certainly an issue with the documentLoader you're passing in not being able to resolve an associated document that contains a semantically equivalent property to the `proofPurpose` property in the proof of the signed document being verified.

**Comment by smithbk** [comment]
Thanks for the help.  Yes, you were correct.  I was returning the incorrect values from my doc loader.
